### ISSUE TITLE
USB-C Connector GCT USB4085 not available anywhere

### ISSUE THREAD

**Issue by LouWii** [coseyfannitutti/discipad#1]
Hi there

Thanks for open sourcing the discipad! I needed to order a few custom PCBs and thought "why not put some Discipad" with them, as a fun side-project.

The problem is, I haven't checked the components availability, thinking this wouldn't be an issue. Well, it turns out one of the most important component is gone, the USB C socket used isn't available anywhere. Does someone know of a drop-in replacement somewhere? Or should we work on replacing it with something else?

I'm afraid my PCB order is f*ed though, the only thing I can do is manually re-wire it to another USB C socket. or maybe try and change it to a standard mini or micro USB.

**Comment by coseyfannitutti** [comment]
Yes, as far as I can see all distributors that I am aware of have them backordered. However, they are all saying they will have more stock within a few weeks. The part is not discontinued, so I don't have any plans to change it on my end at this time.

**Comment by LouWii** [comment]
Ah ok, that's good to know. I'm going to contact my sources and see if they
will eventually get some. Thanks for letting me know

Le sam. 2 nov. 2019 à 08:02, coseyfannitutti <notifications@github.com> a
écrit :
